export const ANTHROPIC_MODEL_NAME = process.env.ANTHROPIC_MODEL_NAME;
export const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
export const SMTP_HOST = process.env.SMTP_HOST;
export const SMTP_PORT = parseInt(process.env.SMTP_PORT || "587");
export const SMTP_USER = process.env.SMTP_USER;
export const SMTP_PASS = process.env.SMTP_PASS;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || "";
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || "";
export const NODE_ENV = process.env.NODE_ENV || "development";
